# @format

version: '3.9'

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod

    image: auth-ms
    environment:
      - PORT=${AUTH_PORT}
      - MONGO_URL=${AUTH_MONGO_URL}
      - SECRET_JWT=${AUTH_SECRET_JWT}
      - NATS_SERVERS=${NATS_SERVERS}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms

    environment:
      - PORT=3001
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod

    image: orders-ms
    environment:
      - PORT=${ORDERS_PORT}
      - POSTGRES_USER=${ORDERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDERS_POSTGRES_DB}
      - POSTGRES_PORT=${ORDERS_POSTGRES_PORT}
      - POSTGRES_HOST=${ORDERS_POSTGRES_HOST}
      - NATS_SERVERS=${NATS_SERVERS}

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - '${PAYMENTS_PORT}:${PAYMENTS_PORT}'
    image: payments-ms
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
      - PORT=${PAYMENTS_PORT}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
